# Generated by Django 5.2.1 on 2025-05-31 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام ژانر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان کتاب')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('published_date', models.DateField(verbose_name='تاریخ چاپ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.genre', verbose_name='ژانر')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx'), models.Index(fields=['author'], name='books_book_author_b941fe_idx'), models.Index(fields=['genre'], name='books_book_genre_i_ccb207_idx'), models.Index(fields=['published_date'], name='books_book_publish_649cd8_idx')],
            },
        ),
    ]
